### ISSUE TITLE
1.0.20 升级到 2.X.X需要注意什么？

### ISSUE THREAD

**Issue by sujiewen** [xaboy/form-create#379]
直接升，直接报错，页不知道什么问题？
InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name. stack=Error: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
    at baseSetAttr (https://localhost:8080/static/js/chunk-vendors.js:282704:8)
    at setAttr (https://localhost:8080/static/js/chunk-vendors.js:282679:5)
    at Array.updateAttrs (https://localhost:8080/static/js/chunk-vendors.js:282634:7)
    at invokeCreateHooks (https://localhost:8080/static/js/chunk-vendors.js:281988:22)
    at createElm (https://localhost:8080/static/js/chunk-vendors.js:281875:11)
    at createChildren (https://localhost:8080/static/js/chunk-vendors.js:281972:9)
    at createElm (https://localhost:8080/static/js/chunk-vendors.js:281873:9)
    at VueComponent.patch [as __patch__] (https://localhost:8080/static/js/chunk-vendors.js:282396:7)
    at VueComponent.Vue._update (https://localhost:8080/static/js/chunk-vendors.js:279839:19)
    at VueComponent.updateComponent (https://localhost:8080/static/js/chunk-vendors.js:279960:10) info=nextTick

**Comment by xaboy** [comment]
这好像不是 form-create 报的错

**Comment by sujiewen** [comment]
但是我form-create从1.0.20升级到2.x.x就报这个错误。。。。。。

**Comment by xaboy** [comment]
是生成表单的时候报错还是运行的时候报错. 如果是生成表单的时候报错,你看看是哪一个规则导致的

**Comment by sujiewen** [comment]
我尝试，发现一个新问题  

vue.runtime.esm.js:1897 TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Vue'
    |     property '$options' -> object with constructor 'Object'
    |     property 'router' -> object with constructor 'VueRouter'
    --- property 'app' closes the circle
    at JSON.stringify (<anonymous>)
    at Handler.isChange (form-create.min.js:7)
    at Handler.onInput (form-create.min.js:7)
    at Render.onInput (form-create.min.js:7)
    at callback (form-create.min.js:7)
    at invokeWithErrorHandling (vue.runtime.esm.js:1863)
    at VueComponent.invoker (vue.runtime.esm.js:2188)
    at invokeWithErrorHandling (vue.runtime.esm.js:1863)
    at VueComponent.Vue.$emit (vue.runtime.esm.js:3903)
    at VueComponent.mounted (index.vue:833)


代码就是在组件返回this对象，以前的版本没有问题，代码如下
mounted() {
    this.$emit('returnObjectBack', this)
  },
