### ISSUE TITLE
vue3 + arco-design 报错

### ISSUE THREAD

**Issue by vsme** [xaboy/form-create#529]
`vue: ^3.2.37`
 `@form-create/arco-design: ^3.1.13`

```vue
<template>
  <div>
    <form-create :rule="rule" />
  </div>
</template>

<script setup>
import FormCreate from "@form-create/arco-design";

const rule = [ { type: 'input', field: 'goods_name', title: '商品名称' } ]
</script>


TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableSpread (form-create.esm.js:195:9)
    at _toConsumableArray (form-create.esm.js:166:98)
    at setup3 (form-create.esm.js:1830:21)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)
    at setupComponent (runtime-core.esm-bundler.js:7120:11)
    at mountComponent (runtime-core.esm-bundler.js:5473:13)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5587:21) null render function
```

**Comment by vsme** [comment]
```
runtime-core.esm-bundler.js:38 [Vue warn]: Invalid prop: type check failed for prop "rule". Expected Array, got Object  
  at <FormCreate ref="fc" rule= {rule: Array(1), __vInternal: 1} option= {slots: {…}, emit: ƒ}attrs: （…）emit: ƒ ()slots: {__vInternal: 1}get attrs: ƒ attrs()[[Prototype]]: Object > 
  at <App>
warn2 @ runtime-core.esm-bundler.js:38
validateProp @ runtime-core.esm-bundler.js:4055
validateProps @ runtime-core.esm-bundler.js:4026
initProps @ runtime-core.esm-bundler.js:3725
setupComponent @ runtime-core.esm-bundler.js:7117
...
（匿名） @ main.ts:22
显示另外 13 个框架
runtime-core.esm-bundler.js:38 [Vue warn]: Unhandled error during execution of setup function 
  at <FormCreate ref="fc" rule= {rule: Array(1), __vInternal: 1} option= {slots: {…}, emit: ƒ} > 
  at <App>
```

**Comment by xaboy** [comment]
@vsme  这样写就可以了
```vue
<template>
  <div>
    <Fc :rule="rule" />
  </div>
</template>

<script setup>
import FormCreate from "@form-create/arco-design";
const Fc = FormCreate.$form();
const rule = [ { type: 'input', field: 'goods_name', title: '商品名称' } ]
</script>
```

**Comment by vsme** [comment]
看到指南更新了
