### ISSUE TITLE
启动报appContext错，demo显示不全

### ISSUE THREAD

**Issue by 00001x** [xaboy/form-create#621]
@form-create/element-ui@3.0

3.0

启动报错node.js:45  TypeError: Cannot read properties of null (reading 'appContext')
    at CreateNode.h (node.js:43:1)
    at CreateNode.make (node.js:39:1)
    at Render.renderRule (render.js:287:1)
    at CustomManager.$r (manager.js:30:1)
    at CustomManager.render (manager.js:110:1)
    at Render.render (render.js:38:1)
    at Handler.render (render.js:21:1)
    at FormCreate.render (index.js:225:1)
    at Proxy.render (formCreate.js:36:1)
    at renderComponentRoot (runtime-core.esm-bundler.js:816:1)
![image](https://github.com/xaboy/form-create/assets/84365910/e0e618eb-097d-45cd-9ea5-ba695b434243)

npm run install
npm run bootstrap

怎么解决

**Comment by xaboy** [comment]
vue是那个版本,我这边检查一下 @zhc644322
