### ISSUE TITLE
Type error: vue.min.js:6 TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by xiaoma8713** [xaboy/form-create#721]
### vue版本 2.6.10

`
global附近:
mergeOptions: function(e, t, n) {
                return t = A(t),
                n && ["page", "onSubmit", "mounted", "reload", "formData", "el"].forEach(function(e) {
                    delete t[e]
                }),
                t.global && (e.global = function(e, t) {
                    return e ? (Object.keys(t || {}).forEach(function(n) {
                        t[n] && (e[n] = se(e[n] || {}, t[n]))
                    }),
                    e) : t
vue.min.js:6 TypeError: Cannot read properties of undefined (reading 'global')
    at V.mergeOptions (form-create.min.js:7:85281)
    at V.initOptions (form-create.min.js:7:85071)
    at new V (form-create.min.js:7:83284)
    at a.beforeCreate (form-create.min.js:7:33182)
    at He (vue.min.js:6:11397)
    at Yt (vue.min.js:6:25339)
    at t._init (vue.min.js:6:32772)
    at new a (vue.min.js:6:30548)
    at vue.min.js:6:19469
    at init (vue.min.js:6:19500)

api附近：
beforeCreate: function() {
                var t = this;
                this.formCreate = new e(this),
                Object.keys(this.formCreate.prop).forEach(function(e) {
                    D(t.$options[e], t.formCreate.prop[e])
                }),
                this.$emit("beforeCreate", _this.formCreate.api())_
            },
            created: function() {
                var e = this
                  , t = this
                  , n = this.formCreate.api()
                  , r = function() {
                    var e = L(t, t.$pfc);
                    if (e)
                        if (t.isMore) {
                            var r = $(e.getS

vue.min.js:6 TypeError: Cannot read properties of undefined (reading 'api')
    at a.created (form-create.min.js:7:33393)
    at He (vue.min.js:6:11397)
    at Yt (vue.min.js:6:25339)
    at t._init (vue.min.js:6:33005)
    at new a (vue.min.js:6:30548)
    at vue.min.js:6:19469
    at init (vue.min.js:6:19500)
    at vue.min.js:6:56519
    at f (vue.min.js:6:56795)
    at h (vue.min.js:6:57383)

render附近：
ctxInject: {},
                    updateValue: JSON.stringify(this.value || {}),
                    isMore: !!this.inFor
                }
            },
            render: function() {
                return this.formCreate.render()
            },
            methods: {
                _refresh: function() {
                    ++this.unique

vue.min.js:6 TypeError: Cannot read properties of undefined (reading 'render')
    at a.render (form-create.min.js:7:32437)
    at e._render (vue.min.js:6:35481)
    at a.r (vue.min.js:6:68178)
    at fn.get (vue.min.js:6:26768)
    at new fn (vue.min.js:6:26686)
    at vue.min.js:6:68192
    at wn.$mount (vue.min.js:6:68339)
    at wn.$mount (vue.min.js:6:93554)
    at init (vue.min.js:6:19508)
    at vue.min.js:6:56519
`

**Comment by xaboy** [comment]
可能是组件没有正常挂载, 文档: https://form-create.com/v2/guide/mount.html
